Repository S4ND1X/oh_team2, pull requests merged in 2021-09, with the labels that each got.

#1 add readme template
  README.md
Labels: documentation

#2 set up boilerplate code for Flask server
  .DS_Store
  app/__init__.py
Labels: enhancement

#14 add python linting check when push or pull
  .github/workflows/lint.yml
  app.py
Labels: Code quality

#15 added content, more media queries, added styling
  landingPage/index.html
  landingPage/style.css
Labels: enhancement

#19 updated readMe
  README.md
Labels: documentation

#20 add jorge portafolio html, static folder and route on app.py
  app.py
  static/css/jorge.css
  static/img/365days.jpg
  static/img/MLH_Logo.svg
  static/img/clubgda.png
  static/img/dev_george.png
  static/img/github-icon.png
  static/img/github.svg
  static/img/jiit.jpeg
  static/img/mlh_fellowship.jpg
  static/img/tec.png
  static/js/jorge.js
  templates/base.html
  templates/jorge.html
Labels: enhancement

#22 fixed file structure, added routing for individual profile, refactor …
  app.py
  assets/.DS_Store
  landingPage/index.html
  long_phan_portfolio/.DS_Store
  long_phan_portfolio/long_phan.html
  myPortfolio/onyemowo.html
  static/css/landing_page.css
  static/css/long_phan.css
  static/css/onyemowo.css
  static/font-mfizz-2.4.1/font-mfizz.css
  static/font-mfizz-2.4.1/font-mfizz.eot
  static/font-mfizz-2.4.1/font-mfizz.svg
  static/font-mfizz-2.4.1/font-mfizz.ttf
  static/font-mfizz-2.4.1/font-mfizz.woff
  static/font-mfizz-2.4.1/preview.html
  static/img/448cc5c68de2e2f8a6194f77345a3b9e.jpg
  static/img/auxify.png
  static/img/long_phan_avatar.jpg
  static/img/sound_quest_project.png
  static/img/teamPhoto.jpg
  templates/landing_page.html
  templates/long_phan.html
  templates/onyemowo.html
Labels: Code quality

#25 fix folder structure for heroku deployment
  Procfile
  app/.pyre_configuration
  app/__init__.py
  app/pysa-runs/taint-metadata.json
  app/pysa-runs/taint-output.json
  app/sapp.db
  app/static/css/jorge.css
  app/static/css/landing_page.css
  app/static/css/long_phan.css
  app/static/css/onyemowo.css
  app/static/font-mfizz-2.4.1/font-mfizz.css
  app/static/font-mfizz-2.4.1/font-mfizz.eot
  app/static/font-mfizz-2.4.1/font-mfizz.svg
  app/static/font-mfizz-2.4.1/font-mfizz.ttf
  app/static/font-mfizz-2.4.1/font-mfizz.woff
  app/static/font-mfizz-2.4.1/preview.html
  app/static/img/365days.jpg
  app/static/img/448cc5c68de2e2f8a6194f77345a3b9e.jpg
  app/static/img/MLH_Logo.svg
  app/static/img/auxify.png
  app/static/img/clubgda.png
  app/static/img/dev_george.png
  app/static/img/github-icon.png
  app/static/img/github.svg
  app/static/img/jiit.jpeg
  app/static/img/long_phan_avatar.jpg
  app/static/img/mlh_fellowship.jpg
  app/static/img/sound_quest_project.png
  app/static/img/teamPhoto.jpg
  app/static/img/tec.png
  app/static/js/jorge.js
  app/templates/base.html
  app/templates/jorge.html
  app/templates/landing_page.html
  app/templates/long_phan.html
  app/templates/onyemowo.html
  requirements.txt
  wsgi.py
Labels: enhancement

#26 First release for Devopost Submission
  .DS_Store
  .github/workflows/lint.yml
  Procfile
  README.md
  app/.pyre_configuration
  app/__init__.py
  app/pysa-runs/taint-metadata.json
  app/pysa-runs/taint-output.json
  app/sapp.db
  app/static/css/jorge.css
  app/static/css/landing_page.css
  app/static/css/long_phan.css
  app/static/css/onyemowo.css
  app/static/font-mfizz-2.4.1/font-mfizz.css
  app/static/font-mfizz-2.4.1/font-mfizz.eot
  app/static/font-mfizz-2.4.1/font-mfizz.svg
  app/static/font-mfizz-2.4.1/font-mfizz.ttf
  app/static/font-mfizz-2.4.1/font-mfizz.woff
  app/static/font-mfizz-2.4.1/preview.html
  app/static/img/365days.jpg
  app/static/img/448cc5c68de2e2f8a6194f77345a3b9e.jpg
  app/static/img/MLH_Logo.svg
  app/static/img/auxify.png
  app/static/img/clubgda.png
  app/static/img/dev_george.png
  app/static/img/github-icon.png
  app/static/img/github.svg
  app/static/img/jiit.jpeg
  app/static/img/long_phan_avatar.jpg
  app/static/img/mlh_fellowship.jpg
  app/static/img/sound_quest_project.png
  app/static/img/teamPhoto.jpg
  app/static/img/tec.png
  app/static/js/jorge.js
  app/templates/base.html
  app/templates/jorge.html
  app/templates/landing_page.html
  app/templates/long_phan.html
  app/templates/onyemowo.html
  requirements.txt
  wsgi.py
Labels: enhancement
